[package]
name = "api"
version = "0.1.0"
authors = ["The CodeMountain Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.4", features = ["postgres", "chrono", "r2d2"] }
dotenv = "0.15.0"
actix-web = "3"
actix-web-validator = "2"
validator = { version = "0.12", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
jsonwebtoken = "7"
derive_more = "0.99.0"
chrono = { version = "0.4", features = ["serde"] }
bcrypt = "0.8"
r2d2 = "0.8.9"