FROM rust:latest

ENV DATABASE_URL=postgres://postgres:postgres@postgres:5432/codemountain_dev

WORKDIR /server

COPY ./docker-helpers ./docker-helpers
COPY ./migrations ./migrations
COPY ./.env ./.env
COPY ./Cargo.lock ./
COPY ./Cargo.toml ./
COPY ./diesel.toml ./

RUN mkdir ./src

RUN echo "fn main() {}" > src/main.rs

RUN cargo build --release

RUN cargo install diesel_cli --no-default-features --features postgres

RUN apt update

RUN apt install postgresql -y

RUN USER=root rm -rf ./src/*.rs

COPY ./email_templates ./email_templates

COPY ./src ./src

RUN rm -rf ./target/release/deps/api*
RUN cargo build --release

EXPOSE 8080

CMD ["sh", "-c", "./docker-helpers/dev/wait-for-postgres.sh && diesel migration run && ./target/release/api"]