FROM rust:latest

WORKDIR /server

COPY ./docker-helpers ./docker-helpers
COPY ./migrations ./migrations
COPY ./Cargo.lock ./
COPY ./Cargo.toml ./
COPY ./diesel.toml ./

RUN mkdir ./src

RUN echo "fn main() {}" > src/main.rs

RUN cargo build

RUN cargo install diesel_cli --no-default-features --features postgres

RUN apt update

RUN apt install postgresql -y

RUN DEBIAN_FRONTEND=noninteractive apt install postfix -y

RUN USER=root rm -rf ./src/*.rs

COPY ./email_templates ./email_templates

COPY ./src ./src

ENV DATABASE_URL=postgres://postgres:postgres@postgres:5432/codemountain_test
ENV TEST_ENV=true

CMD ["sh", "-c", "./docker-helpers/test/prepare-test-env.sh && diesel migration run && psql ${DATABASE_URL} -f ./docker-helpers/test/insert_test_data.sql && cargo test"]