[package]
name = "sandbox"
version = "0.1.0"
edition = "2018"
authors = ["The CodeMountain Developers"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seccomp = "0.1"
libc = "0.2"