name: Sandbox Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        platform: x64
    - name: Installing Python
      run: sudo apt install python3
    - name: Compiling Sandbox Executable
      run: cd sandbox/client && ./build.py
    - name: Build
      run: cd sandbox/client && cargo build
    - name: Run tests
      run: cd sandbox/client && sudo -E cargo test --verbose
