name: Sandbox Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SANDBOX_UID: 1002
  SANDBOX_GID: 1002

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up gcc and g++
      run: sudo apt update && sudo apt install -y clang cmake
    - name: Installing libseccomp-dev
      run: sudo apt install libseccomp-dev
    - name: Making dummy user
      run: sudo adduser -u 1002 dummy
    - name: Compiling Sandbox Executable
      run: cd sandbox && ./build.py --debug
    - name: Build
      run: cd sandbox/client && cargo build -- --test-threads=1
    - name: Run tests and print logs
      run: cd sandbox/client && sudo -E $(which cargo) test --verbose; cat logs/*
