name: Server API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:a3b2c100@127.0.0.1/codemountain_test

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up postgres
      run: |
        sudo apt update
        sudo apt install -y postgresql
        sudo service postgresql restart && sleep 3
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'a3b2c100';"
        sudo -u postgres psql -c "CREATE DATABASE codemountain_test;"
        sudo service postgresql restart && sleep 3
    - name: Build the server
      run: |
        cd server/api
        cargo build
    - name: Install Diesel CLI
      run: |
        cargo install diesel_cli --no-default-features --features postgres
    - name: Run migrations
      run: |
        cd server/api
        diesel migration run
    - name: Add test values
      run: |
        sudo -u postgres psql -c "INSERT INTO USERS(uid, firstname, lastname, username, email, password) VALUES (25, 'John', 'Doe', 'johndoe', 'john_doe@example.com', '$2b$12$dDuxYtY4gfHBrxzZr6d6k.hHI1r9AAOLdTWC1rNSXKULwrpeiZYti')
    - name: Run tests
      run: |
        cd server/api
        cargo test
